# Block names from
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
config: true
worlds:
  - world
above_y: 54
natural_blocks:
  - SHORT_GRASS
  - TALL_GRASS
  - SANDSTONE
  - RED_SANDSTONE
  - GRAVEL
  - STONE
  - DIRT_PATH
natural_tags:
  - leaves
  - overworld_natural_logs
  - sand
  - dirt
