name: Creepair
main: im.wma.dev.creepair.Creepair
version: ${version}
website: http://wma.im
api-version: 1.16 # Because of this Creepair is not compatible with verisons lower than 1.14
commands:
  creepair:
    description: Returns the plugin version
    usage: /creepair
  creepair list:
    description: Returns the current Creepair Block List config
    usage: /creepair list
    permission: creepair.list
  creepair add:
    description: Add a new Material to the Creepair config
    usage: /creepair add (MATERIAL NAME)
    permission: creepair.add
  creepair reload:
    description: Reload Creepair config
    usage: /creepair reload
    permission: creepair.reload
permissions:
  creepair.list:
    description: Allows list command
    default: op
  creepair.add:
    description: Allows add command
    default: op
  creepair.reload:
    description: Allows reloading
    default: op
  creepair.*:
    description: Wildcard permission
    default: op
    children:
      creepair.add: true
      creepair.list: true
      creepair.reload: true